### ISSUE TITLE
Virtual stigmergy not casting to string on put

### ISSUE THREAD

**Issue by xgroleau** [MISTLab/BittyBuzz#7]
Hi, I am not sure if the stigmergy is only supposed to work with strings or int and floats are supported too. It seems that on a put, when no entry are found,  the key object is not casted to a string, resulting to a key that is not a string. Rendering impossible to match with a get since the get casts the key to a string.

In bbzvstig_put in the [vstig.c file at line 168](https://github.com/MISTLab/BittyBuzz/blob/6b8c4bbfc2daa9eb6edc28501a97e4dfa17d8590/src/bittybuzz/bbzvstig.c#L168) there is no cast to a string

But on a get the key is always cast to a string. so this bzz code would not work

```
function init() {
  stig = stigmergy.create(0);
  # Sending it
  if(id == 1){
    stig.put(1, 42); # Not cast to a string
  }
}

function step() {
  if(id == 2){
    # Lets assume the stigmergy was update
    var value = stig.get(1); # Key get cast to a string
    assert_true(value == 42);
  }
}
```

Again I am not sure if this is intended and only strings are supported. The documentation is a bit laking on the doku wiki

**Comment by beltrame** [comment]
I think this asymmetry should not be there, I'll double check on Buzz senior and see what I can do about this

**Comment by beltrame** [comment]
@Belkharym I don't think the cast is necessary, can you confirm?

**Comment by Belkharym** [comment]
One of the measures we used to reduce the amount of memory used by BittyBuzz was to only allow strings for the key. Internally, we only keep track of the string id, and all keys passed to get or put are interpreted as string ids. We thought we put this detail in the documentation, but it's apparently something we missed.

**Comment by beltrame** [comment]
The result is that keys can only be strings, README will be updated so we can close this issue.
